#!/usr/bin/env bash
#
# triageRush - background music transcode
# ----------------------------------------
# Turns full-quality source MP3s into the tiny, AM-radio-sounding, ANONYMOUS
# files the game ships. Same idea as _asset-audit-and-resize does for the
# art: the originals are kept aside, the delivery copies are generated.
#
# THE RECIPE (chosen by John, 2026-08-07, by ear, from the seven-way
# listening test in _mockups/audio-bitrate-test.html - he picked "G, heavy
# AM"):
#
#   highpass 400 Hz + lowpass 3.2 kHz   the AM-radio band. A cheap
#                                       transistor radio in the corner of
#                                       the waiting room.
#   acompressor 6:1 @ -16 dB            broadcast-style squash - AM stations
#                                       compress hard, and it keeps the
#                                       music sitting at one steady level
#                                       under the game sounds.
#   24 kbps, mono, 22.05 kHz            37 MB -> ~2.5 MB for all five tracks.
#
# WHY 24 kbps IS NOT A MISTAKE: low bitrates wreck the treble first, and the
# lowpass has already thrown that treble away, so the encoder has nothing
# left to ruin. The same 24 kbps applied to UNFILTERED music sounds swirly
# and underwater - that comparison is D vs E on the test page. Filtering
# first is what buys the small file.
#
# THE FILTER IS BAKED IN, permanently. To change the sound, re-run this
# script against the originals; do not try to undo it in the game.
#
# ANONYMITY IS PART OF THE JOB, not a nicety. The delivered files are named
# track-NN.mp3 and carry NO metadata, because these are copyrighted
# recordings sitting in a public repository. Renaming alone would have been
# pointless: the source files' ID3 tags named the song, the artist, the
# album, the label and the catalog number. -map_metadata -1 removes all of
# it. If you add tracks, keep both halves of this - neutral name AND
# stripped tags.
#
# THE PLAY ORDER IS THE TABLE BELOW, not the source filenames. track-01
# plays first. To reorder, reorder the table and re-run. To add a track,
# drop the source into _originals-untreated/, add a line, re-run, and add
# the new file to ASSETS.music.tracks in assets.js.
#
# Usage:  bash transcode-music.sh
# Needs:  ffmpeg with libmp3lame (any recent full build).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AUDIO_DIR="$SCRIPT_DIR/../audio"
SOURCE_DIR="$AUDIO_DIR/_originals-untreated"

# Play order, chosen by John 2026-08-07. One entry per line:
#   <output track number>|<source filename, without .mp3>
PLAYLIST=(
  "01|01 Superman (Scrubs, Lazlo Bane)"
  "02|02 All in My Head (Scrubs, Shawn Mullins)"
  "03|15 Overkill (Scrubs, Colin Hay)"
  "04|03 Fresh Feeling (Scrubs, Eels)"
  "05|14 Scrubs (End Credit Score) (Scrubs, Jan Stevens)"
)

# The whole recipe, in one place, so the comment above and the command below
# can never drift apart.
FILTER="highpass=f=400,lowpass=f=3200,acompressor=threshold=-16dB:ratio=6:attack=5:release=80"
BITRATE="24k"
SAMPLE_RATE="22050"

# Kept OUT of the repository (see .gitignore) so the mapping from neutral
# name back to real song never gets published.
MAP_FILE="$SOURCE_DIR/track-mapping.txt"

if [ ! -d "$SOURCE_DIR" ]; then
  echo "No source folder: $SOURCE_DIR"
  echo "Put the full-quality MP3s there and run again."
  exit 1
fi

echo "Transcoding ${#PLAYLIST[@]} track(s) with: $FILTER"
echo "            $BITRATE mono @ $SAMPLE_RATE Hz, metadata stripped"
echo

echo "triageRush music - which track-NN is which song." > "$MAP_FILE"
echo "Generated by transcode-music.sh. NOT published (see .gitignore)." >> "$MAP_FILE"
echo "" >> "$MAP_FILE"

for entry in "${PLAYLIST[@]}"; do
  number="${entry%%|*}"
  base="${entry#*|}"
  source="$SOURCE_DIR/${base}.mp3"
  target="$AUDIO_DIR/track-${number}.mp3"

  if [ ! -f "$source" ]; then
    echo "  MISSING: $source"
    exit 1
  fi

  # -map 0:a drops the embedded cover art, which is a surprising slice of
  #   the original file size and is never shown by the game.
  # -map_metadata -1 drops every ID3 tag. Without it the file still
  #   announces the song, the artist, the album and the label.
  ffmpeg -v error -y -i "$source" \
    -map 0:a \
    -map_metadata -1 \
    -af "$FILTER" \
    -c:a libmp3lame -b:a "$BITRATE" -ar "$SAMPLE_RATE" -ac 1 \
    "$target"

  source_kb=$(( $(stat -c%s "$source") / 1024 ))
  target_kb=$(( $(stat -c%s "$target") / 1024 ))
  printf '  track-%s  %-52s %6d KB -> %5d KB\n' \
    "$number" "${base:0:52}" "$source_kb" "$target_kb"
  printf 'track-%s.mp3  =  %s\n' "$number" "$base" >> "$MAP_FILE"
done

echo
echo "Done. Delivery files are in: $AUDIO_DIR"
echo "Name mapping written to:     $MAP_FILE"
